### ISSUE TITLE
This isn't GitHub's fault

### ISSUE THREAD

**Issue by aw3stin1** [1995parham/github-do-not-ban-us#38] opened 2019-07-26 15:33 UTC
I feel like this language seems to be blaming GitHub. This isn't really GitHub's fault.

The issue is that GitHub is a U.S. based company and the U.S. is really starting to ratchet up sanctions on Iran. GitHub can't really do anything about these sanctions and they are inviting legal trouble from the U.S. if they don't comply.

It's an unfortunate situation but I don't think there is anything GitHub can do about it. You can't really blame GitHub for this. Their hands are pretty much tied.

**Comment by BelegCuthalion** [comment] 2019-07-26 15:36
I agree. They Github can't do anything about this situation. They can instead stop bragging with that rainbow flag on their logo, can't they?

**Comment by BelegCuthalion** [comment] 2019-07-26 15:38
I suggest to change the section "Notes for Github" to urge Github to either reject compliance with "internationally illegal" sanctions, or publicly announce their decision, so that everyone knows.

**Comment by pesehr** [comment] 2019-07-26 15:46
@aw3stin1 
Github blocked our repositories without any previous alert.
Whose fault is it?

**Comment by aw3stin1** [comment] 2019-07-26 15:51
https://help.github.com/en/articles/github-and-trade-controls

**Comment by aw3stin1** [comment] 2019-07-26 16:02
@pesehr Whose fault is it? As GitHub is not the U.S. government, I would say... not GitHub's.

From the moment GitHub determined that providing service to Iran was a violation of U.S. sanctions, any extension of service would have been a knowing and willful violation of U.S. sanctions and trade controls. So, to provide notice and an extension of service would have been illegal and would have opened them to legal action by the U.S. government.

Again, this is an unfortunate situation but blaming GitHub is actually counter-productive as it takes attention and effort away from the true cause of the issue. This wasn't GitHub's choice.

**Comment by PurHur** [comment] 2019-07-26 16:09
@pesehr what do you expect? That microsoft is breaking the law? That wont happen. You have to address your arguments to the us goverment no one else. They didnt wanted that too but they have to.

**Comment by SamanFekri** [comment] 2019-07-26 16:17
@aw3stin1 the private repository in github with less than 3 collaborators are free service since jan 7, 2019. So we do not trade with github for them. Github can release our repositories. 
Check [this](https://github.blog/2019-01-07-new-year-new-github/)

**Comment by mirhmousavi** [comment] 2019-07-26 16:28
if its realy 

> I feel like this language seems to be blaming GitHub. This isn't really GitHub's fault.
> 
> The issue is that GitHub is a U.S. based company and the U.S. is really starting to ratchet up sanctions on Iran. GitHub can't really do anything about these sanctions and they are inviting legal trouble from the U.S. if they don't comply.
> 
> It's an unfortunate situation but I don't think there is anything GitHub can do about it. You can't really blame GitHub for this. Their hands are pretty much tied.

Really? so why Google won't ban Iranians? Does just Github want to obey the law?

**Comment by pesehr** [comment] 2019-07-26 16:34
@aw3stin1 @PurHur 
Guys, Github is not the first organization that restricts us and won't be the last one. We had the same problem with Gitlab.com. I know that the US government forces them, but Github chose the worst way. This law is so stupid, but at least they should inform us about that well.
In the Gitlab case, they sent several emails to us, and after that restricted our accesses, they did not block our codes. 
I don't know where are you from, but how can you trust a company that gives himself this permission to block your codes?
Some of my repositories which have been blocked are my university projects. I'm a student and using educational plan. I didn't have trade with Github or the US companies. Can you imagine that one day you wake up and find out you have no access to your projects?
I think it's better to be our voice and support us.

**Comment by aw3stin1** [comment] 2019-07-26 16:34
@SamanFekri Providing services, whether free or paid, is still providing services. While U.S. sanctions and trade controls do apply to moving money to/from sanctioned countries, they also apply to "the export of services." A service is a service - free or paid.

**Comment by aw3stin1** [comment] 2019-07-26 16:37
@pesehr I **don't** trust 3rd parties with my important work and projects. I keep backups of everything I don't want to lose.

**Comment by 24js** [comment] 2019-07-26 16:38
The least they could've done was let us create a backup and download our repositories 
My Projects are gone :cry:, I didn't have a local backup from several of my projects

**Comment by SimplyCodin** [comment] 2019-07-26 16:42
This is kinda your fault for not reading the terms of service and policies of a product that build your projects in. It's unfortunate that you lost an avenue to publish your code but you should have backups in the form of a local repository on your device

**Comment by PurHur** [comment] 2019-07-26 16:42
>I don't know where are you from
Im from inside the EU and we don't use US 3 party software that much because they give a fuck about your data. Guess what we are doing here in the green EU without sanctions?

> \but how can you trust a company that gives himself this permission to block your codes?
Thrust the usa? Thats sounds even more wrong when you are a citizen of an "enemy state". Even we dont thrust them.
Dont use github if you live in such sort of country and heavly rely on. Its your fault setting up your infrastructure that depended on github.

>Some of my repositories which have been blocked are my university projects.
My universities had always their own repo servers like it should be in every organisation/institution.


Gitlab is free. Host your own gitlab for your own important stuff. Its not much todo if you use docker.

**Comment by aw3stin1** [comment] 2019-07-26 16:43
> if its realy
> 
> > I feel like this language seems to be blaming GitHub. This isn't really GitHub's fault.
> > The issue is that GitHub is a U.S. based company and the U.S. is really starting to ratchet up sanctions on Iran. GitHub can't really do anything about these sanctions and they are inviting legal trouble from the U.S. if they don't comply.
> > It's an unfortunate situation but I don't think there is anything GitHub can do about it. You can't really blame GitHub for this. Their hands are pretty much tied.
> 
> Really? so why Google won't ban Iranians? Does just Github want to obey the law?

I assume Google decided they are willing to pay the millions of dollars it will take to defend themselves in court if it comes to that.

**Comment by xunien** [comment] 2019-07-26 16:43
And what if Github server can be hosted outside of the US ? IMO laws are apply only by servers location, I mean not the service by itself, but I’m probably wrong.

**Comment by PurHur** [comment] 2019-07-26 16:46
Also git is very good decentralized to make it work good. Do you guys did not have a single backup of the repos? Not a single one anywhere? Thats you fault. What if microsoft decides to close this thing? Omg People...

**Comment by SamanFekri** [comment] 2019-07-26 16:46
@aw3stin1 
Github says:”we can offer free code collaboration services to developers in sanctioned markets. We believe that offering those free services supports U.S. foreign policy of encouraging the free flow of information and free speech in those markets.”

**Comment by BelegCuthalion** [comment] 2019-07-26 16:47
I agree with @aw3stin1 @PurHur.
I don't blame Github–or any other company–for giving service to anyone they want, based on nationality, residence, ethnicity, gender, wealth, criminal record, anything. It's their service, they do whatever they want with it.
I just can't tolerate them acting like freedom knights protecting inclusion and diversity.
Nor I want to hear a US official claim "sanctions are not affecting ordinary civilians" and "we are not restricting the free flow of communication and information", without any concern of being questioned.

So my suggestion is still there: Demand Github to either:
  - release our code, or
  - announce their decision publicly
So at least they can't benefit from their appeal anymore.

**Comment by theMadBadger022** [comment] 2019-07-26 16:48
@xunien yes, this is why possibly sourcehut man and Bitbucket doesn't restrict users due to their locations, and why self-hosted services like gitea and pagure is dependant on their location as well. The only solution to this issue is federation by means of switching to alternatives and no centralised data-holding, that is never a good idea regardless.

**Comment by PurHur** [comment] 2019-07-26 16:48
I did not say that github could not implement a download button for such repos to get their ass out of this anger. But this is a political issue. Speak to the politicians about it.

**Comment by aw3stin1** [comment] 2019-07-26 16:49
> @aw3stin1
> Github says:”we can offer free code collaboration services to developers in sanctioned markets. We believe that offering those free services supports U.S. foreign policy of encouraging the free flow of information and free speech in those markets.”

You have completely taken that portion of their language out of context. The entirety of what they said was, "As U.S. trade controls laws evolve, we will continue to work with U.S. regulators about the extent to which we can offer free code collaboration services to developers in sanctioned markets."

In other words, they are doing their best to work with lawmakers to try to provide these services legally if possible.

**Comment by SamanFekri** [comment] 2019-07-26 16:56
@aw3stin1 👍🏻👍🏻
I ask github at least make a download button then we can download our codes

**Comment by ovflowd** [comment] 2019-07-26 17:03
I really want to support the cause of the Iranians, but being honest, what y'all are doing isn't right. (Neither what the U.S government did), saying that, it was a decision made by the government.

Some restrictions are applied, that's really unfortunate, but creating this repository sounds more a calling for "arms". Even if you get support by developers around the world, there nothing that our support to this repository would affect the action that GitHub had to take in order to follow the US law.

Because if not, if GitHub just didn't wanted to obey the U.S law, the government can take actions like shutting down GitHub temporarily from the Internet.

I would really support if y'all that want something to change to actually trigger in the proper channels. Why Google doesn't ban Iran? It's not about being banned or not, actually your GitHub account isn't banned, you're just restricted to perform actions that result in **trading**, like private repositories.

And being honest, and I'm really sorry for saying this, I can't simpatize in the way how y'all (authors of the repository) are doing "things". We're trying to explain why creating this repository will not, or probably not, make any kind of difference. And sometimes, I have seen harsh answers and not polite answers at all.

Even if your account is restricted, it doesn't mean that you shouldn't be respectful and polite with your peers. We're all trying to help.

Please, use the proper social network channels or proper diplomatic channels to do that. Just crying and blaming GitHub really will not change anything. GitHub hands are tied up.

And PLEASE don't even try to SAY or ASSUME that GitHub is doing that "so quickly" and "not giving a warning" or whatever. PLEASE just DON'T assume things. Ask for GitHub support, or just talk with them, for example @ Twitter.

Non-employees of GitHub can't give you an answer, so this repository is pointless. And offensive, because that's not how we grown up people try to solve things.

I would totally give 👍 if this repository was different. Instead of accusing and blaming... Y'all (repository authors) try to actually have a different approach.

I wish the best for y'all (the Iranians). I hope that the US government undo their action because that's just unfair. Everyone should be able to contribute, and well, even with this restriction you still can contribute to open source. You're just blocked to do anything that it's "private repositories". Because on the "mind/head" of the US government it could be used for something "bad".

Keep up the good work :)

**Comment by BelegCuthalion** [comment] 2019-07-26 17:09
@ovflowd Personally, I don't even expect Github to take any actions at all. What I hope to achieve is just **informing** people around the world. This is the point of this repo IMO.
And I agree, the tune should not be just about blaming Gitlab.

> I agree with @aw3stin1 @PurHur.
> I don't blame Github–or any other company–for giving service to anyone they want, based on nationality, residence, ethnicity, gender, wealth, criminal record, anything. It's their service, they do whatever they want with it.
> I just can't tolerate them acting like freedom knights protecting inclusion and diversity.
> Nor I want to hear a US official claim "sanctions are not affecting ordinary civilians" and "we are not restricting the free flow of communication and information", without any concern of being questioned.
> 
> So my suggestion is still there: Demand Github to either:
> 
>     * release our code, or
> 
>     * announce their decision publicly
>       So at least they can't benefit from their appeal anymore.

**Comment by ovflowd** [comment] 2019-07-26 17:12
@BelegCuthalion creating a GitHub repo doesn't inform people. I'll already seen some tweets and medium posts. In some moment GitHub will need to make a public announce, of course.

Still, good luck, I hope US undo their sanction.; Like with Huawei/China. It's just disgusting some of the stuff they are doing....

But here, through Issues, this isn't the proper place to discuss it. And like I said, it offends the platform. It is a free collaboration/coding platform. We shouldn't post political stuff here, at all.

:)

**Comment by 1995parham** [comment] 2019-07-26 17:12
@ovflowd I have created this repository in the first place to acknowledge the Github that we want to contribute and we want to be seen by other developers. Github didn't specify any further action and It can even close our public repositories tomorrow without notifying us. I know some of us being offensive and they do because of their codes and the Github actions. Github support even doesn't answer to us and describe what services they restricted us. So again this repository is simply for informing Github and make them answer to us about their further actions. If you see something offensive I apologize you because we are here to talk and find a way to resolve this and get back to our works.

**Comment by StefanJanssen95** [comment] 2019-07-26 17:39
> And what if Github’s servers can be outside of the US ? IMO laws are apply only by servers location, I mean not the service by itself, but I’m probably wrong.

Yes you are wrong. The company is US based so they have to obey their laws. Even if it wouldn't have to they would. The EU is for example not having a trade ban but a lot of European based companies still follow the trade bam because if they dont they will be banned from trading with the US. 
If a company can make more money from the US then from Iran (which is the case for most international companies) then they will have to follow the ban, whether they leggaly have to or not. 
That's just how capitalism works.

**Comment by andrei-dascalu** [comment] 2019-07-26 19:04
@aw3stin1 the 'no warning' part is definitely github's fault. Sorry, but while they have to abide by what the govt says, it is also a matter of how you do it.
"hey, we must enforce restrictions as dictated by the govt. We are sorry, it's not our choice. Those restrictions will enter full force in 24h so you have thst time to find a new home for your code. Sync your local repos, etc"

**Comment by ovflowd** [comment] 2019-07-26 19:10
@andrei-dascalu you're totally wrong. Once the government drop the announce (the law change), every company is obligated the follow it ASAP. They can't make a 24h notice.

Please read more about the law. Blaming GitHub is irritating, and saying that they have no soul or doing that just because "for the sake of being a evil company", C'mon, this is no Hollywood here.

And I personally know a lot of people that work @ GitHub, I definitively KNOW that if they had a manner to help the Iranians without putting themselves in trouble they would have doing it.

And yes, of course GitHub doesn't want to put themselves in trouble, they're not crazy enough to jeopardise the world's biggest "hub" of code, were millions of organisations depend.

Again, it's an unfortunate situation. Again, I don't think this is the proper place to speak about it.

I'm also 99% sure that if you ask @github Twitter they will answer you. Please don't make SUPPOSITIONS without knowing what's the truth behind it. That hurts 😢 

Again, I wish the best for the Iranians and I hope this situation gets solved. 🙏 

But acting like that, will be no good for any parties, and will only make people actually not get supporting your call.

**Comment by StefanJanssen95** [comment] 2019-07-26 19:12
> @aw3stin1 the 'no warning' part is definitely github's fault. Sorry, but while they have to abide by what the govt says, it is also a matter of how you do it.
> "hey, we must enforce restrictions as dictated by the govt. We are sorry, it's not our choice. Those restrictions will enter full force in 24h so you have thst time to find a new home for your code. Sync your local repos, etc"

You are saying not all devs take regular backups? All repos I have participated in are automatically updated to my PCs.

**Comment by aw3stin1** [comment] 2019-07-26 19:15
> @pesehr Whose fault is it? As GitHub is not the U.S. government, I would say... not GitHub's.
> 
> From the moment GitHub determined that providing service to Iran was a violation of U.S. sanctions, any extension of service would have been a knowing and willful violation of U.S. sanctions and trade controls. So, to provide notice and an extension of service would have been illegal and would have opened them to legal action by the U.S. government.
> 
> Again, this is an unfortunate situation but blaming GitHub is actually counter-productive as it takes attention and effort away from the true cause of the issue. This wasn't GitHub's choice.

@andrei-dascalu

**Comment by motakbiri** [comment] 2019-07-26 19:23
@ovflowd I do agree with some parts of your comments, but I have some points.
1) Github is not the first company that restricted our access from its features. Most of the companies just restricted Iran's IPs, and this is acceptable enough for the US government. I believe what Github did, sounds more like flattery.

2) Github restricted all of the users who logged in just one time in Iran, it means we can't use Github even from other countries, but based on the US law companies must not trade with Iran **government** and people (requests) inside Iran. **(actually GitHub is blocking users based on their Nationality)** 

3) Slack did the same thing a few months ago, and after that, they apologized from us. (they continued blocking based on the IPs, not Nationality, which is something we want from Github too. you can read more about it here: https://slackhq.com/an-apology-and-an-update)

4)
>And PLEASE don't even try to SAY or ASSUME that GitHub is doing that "so quickly" and "not giving a warning" or whatever. PLEASE just DON'T assume things. Ask for GitHub support, or just talk with them, for example @ Twitter.

I am not sure what you meant by assuming, this is exactly what happened. They didn't give us a warning, and also they are not answering to our posts on social media like twitter and medium. You can find a lot of not answered tweets about this situation on twitter.

5) the main purpose of this repo is making people aware of what is happening to us, and I think it did it. Please don't consider this as accusing and blaming and please don't call it pointless.

**Comment by BelegCuthalion** [comment] 2019-07-26 19:29
@ovflowd can you please clarify what do you mean by "the law change"? bc I'm not sure if this has happened recently.

**Comment by ovflowd** [comment] 2019-07-26 19:40
@motakbiri I totally understand your point and giving your points I totally relate and agree based in your comment.

If GitHub is really not answering the tweets and comments, that's an unfortunate situation and really sad one. Probably they just can't answer without having a "green light" from a high executive, because that's a real _complicated_ situation.

I didn't knew they were _blocking_ by Nationality, I remember Slack was doing that also and I agree that they should have apologised, because they just simply banned everyone from Iran access and/org Nationality. That's not the case of GitHub, were they only blocked the "trading" related features.

     the main purpose of this repo is making people aware of what is happening to us, and I think it did it. Please don't consider this as accusing or blaming and please don't call it pointless.

I do agree with you, but the README sounds different. And GitHub is not banning anyone. 

    can you please clarify what do you mean by "the law change"? bc I'm not sure if this has happened recently.

I'm not aware if Iran was banned recently, that's what I said about the law change, but if the ban isn't something new, so the ban itself should be considered a warning for anyone using software, platforms and hardware's that may be affected because of being/accessing from Iran.

Being honest, this **this** is a very delicated situation and thing, I would rather for not absent further comments because I don't want disseminate any kind of hate.

I really hope US stop this ******* thing, and allow once again the Iran people and the people accessing from Iran to have their rights. What the US government is doing is cowardice.

Good luck, again 🙏

**Comment by 1995parham** [comment] 2019-07-26 19:46
@ovflowd Thanks for your contribution to this discussion. We will update README to be more precise about the goal of this repository.

**Comment by ovflowd** [comment] 2019-07-26 19:51
Thank you, @1995parham ✨

**Comment by alisharifi2000** [comment] 2019-07-26 20:25
Due to American trade law not all Iranian citizen in the sanction list. just some of them.

**Closed** 2019-07-27 03:29 UTC

**Comment by gharabaghi** [comment] 2019-07-27 11:50
This is a nightmare called microsoft!
When micrsoft was not the owner of github we weer using it without problem. although the company made free private repo available but now they are banning some countries. 
I though in open source world every body in all over the world could has access to all the data and code. maybe i was wrong!
But there are some questions. why just some companies in US are banning these countries and why this action is taken in different times in different companies?

**Comment by DanielRuf** [comment] 2019-07-27 17:16
> This is a nightmare called microsoft!

This is not true, GitHub was a US company before Microsoft bought the platform.

**Comment by ShayBox** [comment] 2019-07-27 18:00
Here's a good solution, stop closing every thread that's telling everyone the real reason this is happening, this isn't github or microsofts fault, every US company has to follow this same law, go complain to the government :man_shrugging:

**Comment by alisharifi2000** [comment] 2019-07-27 18:04
@ShayBox US sanctions do not tell all Iranian citizen are banned. they say just some of them should ban.

**Comment by alisharifi2000** [comment] 2019-07-27 18:04
> 
> 
> Here's a good solution, stop closing every thread that's telling everyone the real reason this is happening, this isn't github or microsofts fault, every US company has to follow this same law, go complain to the government 🤷‍♂

US sanctions do not tell all Iranian citizen are banned. they say just some of them should ban.

**Comment by 24js** [comment] 2019-07-27 18:06
> No one did nothing wrong, The problem is they should've informed us to get the f*** out,
> I chose my country Iran when I signed-up most of USA based services give an error that they can't give services to Iran, Cuba, Syria, North Korea, Crimea,... prior to using services
> 
> Github let me create private repositories, Contribute to other Repos ( Private and Public), Suddenly yesterday BOOM, I can't see, download, even delete my repositories the only way out is that I manage to get to another country and prove to Github that I'm not affiliated to my Country, They even ask why did I visit Iran past 24 month :|
> 
> You might say you should've read Github Trade Controls, here is exact quote:
> 
> > GitHub Enterprise Server may not be sold to, exported, or re-exported to any country listed in Country Group E:1 in Supplement No. 1 to part 740 of the EAR or to the Crimea region of Ukraine. This list currently contains Cuba, Iran, North Korea, and Syria, but is subject to change.
> 
> I didn't know that I'm using GitHub Enterprise Server, I thought I'm using Free service
> **bare in mind**, they added this policy **2 days ago** without any notice
> https://web.archive.org/web/*/https://help.github.com/en/articles/github-and-trade-controls
> 
> And next day The entire backup of my projects which I thought it's safe are gone
> 
> In the end, I was sick to my stomach past 24 hours  I came to term with it
> I said to myself it was my fault, I always knew you can't rely on Big Corporates but Had this negligence that Github is different I even supported Microsoft acquisition when my friends were angry and abandoned Github
> It's no one's fault, The way Github handled this situation was wrong

**Comment by ShayBox** [comment] 2019-07-27 18:11
Complain to the government, they had no choice in the matter and couldn't have done it any differently.
Also don't consider any data online safe, any website can be taken down at any time.

**Comment by andrei-dascalu** [comment] 2019-07-30 08:15
@ShayBox @ovflowd sorry but no, Github is at fault. You're right that once the government had the definitive decision of the law Github had to comply but ...

1. the law change is a process. All tech companies monitor the process for changes that might affect their activity so that their company lawyers can prepare challenges when needed. All Github had to do was to notify users that "this change is coming, we may not have a chance, etc".
2. challenge it, since it deprives them of users. Even in the case of a loss, between the judicial decision and whatever final signature is needed there is still some time. A legal challenge also comes with an injunction that suspends the application, so that users will have time to act (as long as Microsoft wants that)
3. even if things happen as they did, Github could still send a message of what happened, rather than people waking up to 404s for no apparent reason. And in that case, Github could still export the code and let people just download it.

Between this and the lack of any challenge, Github's message is that users just don't matter. Apple and Google always challenge the government on decisions that affect users and have managed to kill/delay legislation to that effect, but Microsoft just obeys and worse, doesn't offer even the courtesy of an "I'm sorry" or any message whatsoever.

**Comment by ShayBox** [comment] 2019-07-30 13:52
:man_shrugging: They did what they did, they had to do it, and they're not going to revert it unless the US government changes something, they *could* have gave a bit of a warning, but would that really have mattered? it still would have happened. GitHub has no responsibility to help users that are being sanctioned by the laws that they're being forced to restrict, that's like warning a criminal you're gonna call the police on them, you just don't do it, you don't give criminals a heads up, the same way you don't give the users that were effected by this change a warning, it defeats the point of the change, letting people migrate to a different platform that the government doesn't control is literally the opposite of what they want.

**Comment by BelegCuthalion** [comment] 2019-07-30 16:21
@ShayBox I commented earlier on you issue [here](https://github.com/1995parham/github-do-not-ban-us/issues/505#issuecomment-515747709), and explained why I think your point is irrelevant, and asked if I'm missing anything, which you refused to reply. I did say that I'm agree with you that US gov. is *also* responsible, along with other parties, which are subject to our protest by *other means*. I said there why I think this is just *GitHub's* interpretation of their legal obligations, and why other US services does not think anything less than that counts as

> warning a criminal you're gonna call the police on them

 I also explained why this won't exempt GitHub from other responsibilities, responsibilities that I agree that are inconsistent with what US gov. obligates them, not limited to just "helping users that are being sanctioned", or even providing any service at all; What GitHub is doing is a consequence of what US government is doing, along with many other things, but there are also other aspects to the problem that are yet to be discussed. There are many things we are opposing with what they both are doing, and reducing it to purely compliance with the law seems just apologetic and superficial. **And they are to be discussed separately.** Separation of Concerns. Mixing stuff up just makes confusion and leads to this unilateral point of view.

So if you still think there are no more GitHub could do (or no less they could do not), please comment specifically on the other responsibilities I wrote about in the mentioned issue.

Anyway, as I [said](https://github.com/1995parham/github-do-not-ban-us/issues/505#issuecomment-515747908) about their recent [*"reverts"*](https://github.com/1995parham/github-do-not-ban-us/issues/666) they actually did *after* our protest,

> they probably either gonna face punishments now, or they could do this #666 from the very first.

Or maybe "the law" has changed in the meantime.

**Comment by ovflowd** [comment] 2019-07-31 12:43
I personally think this discussion went too much over. Every human being is free to have their own opinions and think whatever they want, even the truth or the facts being different.

Feel free to blame GitHub. Feel free to blame anyone.

The truth is still different. Remember even GitHub being a company, the company is made by humans that still make mistakes. Would you like if someone blame you for something that you know isn't truth?

Try to check the facts first, really try, please.

I'm literally out of this conversation, for me is enough, this Issue will not go anywhere.

**Comment by BelegCuthalion** [comment] 2019-07-31 16:22
Now I'm really starting to think there is a big misunderstanding here.

This is not about blaming any person or opinion. *"This isn't GitHub's fault"* was claimed, and checking the facts is what exactly we all are (or at least I think I am) trying to do. I just said that *"This"* (what has happened?), *"GitHub's"* (who's?) and *"fault"* (is it wrong?), all have broader meanings—some of which I mentioned—that should be discussed in details, and in fact I don't suppose that "This is GitHub's fault" at all. Then I asked if those who are agreed with the claim have also these other aspects in mind, and if so, would they inform me if the claim still applies to these other aspects too.

There are no "truth" or "facts" in what I said, just questions, which are being totally ignored. Even if there are presumed truths in my questions, for those who aren't agreed with them, I then asked an even simpler question: GitHub did `A` first, and then they did `B`, where `B` addresses some concerns about aspects of *their hypothetical "fault"*, and `A ≠ B`, so

1. Are they violating the law now?
2. Are they still in compliance with the law, but the law has changed meanwhile?
3. Could they do `B` from the beginning and still be in compliance with the law?


But getting no answer (seriously, just a "You are fundamentally wrong and that's all", or even a "Compile Error" would suffice), and still being asked to check the facts, leaves me helpless here. I'm totally lost now.

**Comment by ovflowd** [comment] 2019-07-31 17:31
Just quick note. My comment isn't an answer to your last comment, @belegcuthalion. This is a Issue, with a thread format. If I was specifically talking about you, I would have "mentioned" you.

Flying away.
